version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=Progetto;User Id=carlo00;Password=12345678a;TrustServerCertificate=True;
   
  networks:
      - appnet

networks:
  appnet:
